/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NaestenRouteImport } from './routes/naesten'
import { Route as MenukortRouteImport } from './routes/menukort'
import { Route as IngredienserRouteImport } from './routes/ingredienser'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlleRouteImport } from './routes/alle'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const NaestenRoute = NaestenRouteImport.update({
  id: '/naesten',
  path: '/naesten',
  getParentRoute: () => rootRouteImport,
} as any)
const MenukortRoute = MenukortRouteImport.update({
  id: '/menukort',
  path: '/menukort',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredienserRoute = IngredienserRouteImport.update({
  id: '/ingredienser',
  path: '/ingredienser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlleRoute = AlleRouteImport.update({
  id: '/alle',
  path: '/alle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alle': typeof AlleRoute
  '/auth': typeof AuthRoute
  '/ingredienser': typeof IngredienserRoute
  '/menukort': typeof MenukortRoute
  '/naesten': typeof NaestenRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alle': typeof AlleRoute
  '/auth': typeof AuthRoute
  '/ingredienser': typeof IngredienserRoute
  '/menukort': typeof MenukortRoute
  '/naesten': typeof NaestenRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alle': typeof AlleRoute
  '/auth': typeof AuthRoute
  '/ingredienser': typeof IngredienserRoute
  '/menukort': typeof MenukortRoute
  '/naesten': typeof NaestenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alle'
    | '/auth'
    | '/ingredienser'
    | '/menukort'
    | '/naesten'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alle'
    | '/auth'
    | '/ingredienser'
    | '/menukort'
    | '/naesten'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alle'
    | '/auth'
    | '/ingredienser'
    | '/menukort'
    | '/naesten'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlleRoute: typeof AlleRoute
  AuthRoute: typeof AuthRoute
  IngredienserRoute: typeof IngredienserRoute
  MenukortRoute: typeof MenukortRoute
  NaestenRoute: typeof NaestenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/naesten': {
      id: '/naesten'
      path: '/naesten'
      fullPath: '/naesten'
      preLoaderRoute: typeof NaestenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menukort': {
      id: '/menukort'
      path: '/menukort'
      fullPath: '/menukort'
      preLoaderRoute: typeof MenukortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredienser': {
      id: '/ingredienser'
      path: '/ingredienser'
      fullPath: '/ingredienser'
      preLoaderRoute: typeof IngredienserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alle': {
      id: '/alle'
      path: '/alle'
      fullPath: '/alle'
      preLoaderRoute: typeof AlleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlleRoute: AlleRoute,
  AuthRoute: AuthRoute,
  IngredienserRoute: IngredienserRoute,
  MenukortRoute: MenukortRoute,
  NaestenRoute: NaestenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
