// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
let token = data.session?.access_token

// Refresh token if it's about to expire or missing
if (!token) {
  const { data: refreshed } = await supabase.auth.refreshSession()
  token = refreshed.session?.access_token
}
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
